services:
  frontend:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/home/node
      - node_modules:/home/node/node_modules
      - public_files:/home/node/.public
    depends_on:
      - redis
      - localstack
    command: npm run dev
    env_file:
      - .env
    environment:
      # Core application settings
      NODE_ENV: development
      PORT: 3000

      # Redis configuration
      REDIS_HOST: redis
      REDIS_PORT: 6379
      USE_SINGLE_INSTANCE_CACHE: true

      # CDP Uploader configuration
      CDP_UPLOADER_URL: http://cdp-uploader:7337
      CDP_UPLOADER_BUCKET: ${CDP_UPLOADER_BUCKET:-my-bucket}
      CDP_UPLOADER_STAGING_PREFIX: ${CDP_UPLOADER_STAGING_PREFIX:-staging/}
      CDP_UPLOADER_MAX_FILE_SIZE: ${CDP_UPLOADER_MAX_FILE_SIZE:-26214400}
      CDP_UPLOADER_TIMEOUT: ${CDP_UPLOADER_TIMEOUT:-30000}
      CDP_UPLOADER_RETRY_ATTEMPTS: ${CDP_UPLOADER_RETRY_ATTEMPTS:-3}
      CALLBACK_AUTH_TOKEN: ${CALLBACK_AUTH_TOKEN:-dev-callback-token-12345678901234567890123456789012}

      # URLs for callbacks and forms
      CALLBACK_URL: http://frontend:3000/upload/callback
      SUBMISSION_URL: http://frontend:3000
      FORMS_ENGINE_BASE_URL: http://frontend:3000

      # Azure Storage configuration
      AZURE_STORAGE_ENABLED: ${AZURE_STORAGE_ENABLED:-true}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME}
      AZURE_STORAGE_CONTAINER_NAME: ${AZURE_STORAGE_CONTAINER_NAME:-csvtestjournal2}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_STORAGE_PROCESSING_TIMEOUT: ${AZURE_STORAGE_PROCESSING_TIMEOUT:-300000}

      # AWS/LocalStack configuration (for CDP uploader)
      S3_ENABLED: ${S3_ENABLED:-false}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-test}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-test}
      AWS_REGION: ${AWS_REGION:-eu-west-2}
      S3_ENDPOINT: http://localstack:4566
      SQS_ENDPOINT: http://localstack:4566
    networks:
      - cdpuploader

volumes:
  node_modules:
  public_files:

networks:
  cdpuploader:
    external: true
    name: apha-sdo-frontend_cdpuploader